[package]
name = "apisecond"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
sys = { path = '../sys' }
backend = { path = '../backend' }
ctor = "0.2.6"
once_cell = "1.19.0"
