# should change to your ndk path
# 主要用于指定针对 aarch64-linux-android 目标平台的编译工具链路径。
[target.aarch64-linux-android]
ar = "/Volumes/PSSD/android/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "/Volumes/PSSD/android/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android33-clang"
